[theme]
primaryColor = "#c72979" # El magenta de Makerbox para sliders y botones
backgroundColor = "#f8f9fa" # Fondo gris muy claro para no cansar la vista
secondaryBackgroundColor = "#ffffff" # Fondo blanco para el men√∫ lateral (sidebar)
textColor = "#2d2d2d" # Texto oscuro y legible
font = "sans serif"
